Linked_List: linked_list_reverse.o #Source -> Distination
	g++ linked_list_reverse.o -o Linked_List

linked_list_reverse.o: linked_list_reverse.cpp
	g++ -c linked_list_reverse.cpp

clean:
	rm *.o Linked_List
